bump

diff --git a/.github/actions/wf_specific/xca_ca_handler/enroll_eab/action.yml b/.github/actions/wf_specific/xca_ca_handler/enroll_eab/action.yml
--- a/.github/actions/wf_specific/xca_ca_handler/enroll_eab/action.yml
+++ b/.github/actions/wf_specific/xca_ca_handler/enroll_eab/action.yml
@@ -209,7 +209,7 @@ runs:
       exit 1
     shell: bash
 
-  - name: "EAB - 07 - Enroll acme with challenge validation disabled in kid.json"
+  - name: "EAB - 07a - Enroll acme with challenge validation disabled in kid.json"
     run: |
       sudo rm -rf acme-sh/*
       docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --register-account --server http://acme-srv --accountemail 'acme-sh@example.com' --eab-kid keyid_01 --eab-hmac-key YW5vdXRoZXJfdmVyeV9sb25nX2htYWNfZm9yX2tleWlkXzAxX3doaWNoIHdpbGxfYmUgdXNlZF9kdXJpbmcgcmVncmVzc2lvbg --debug 3
@@ -219,7 +219,7 @@ runs:
       openssl x509 -in acme-sh/acme-sh.acme_ecc/acme-sh.acme.cer -ext extendedKeyUsage -noout | grep "TLS Web Client Authentication, Code Signing"
     shell: bash
 
-  - name: "EAB - 07 - Enroll lego with challenge validation disabled in kid.json"
+  - name: "EAB - 07a - Enroll lego with challenge validation disabled in kid.json"
     run: |
       sudo rm -rf lego/*
       docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego -s http://acme-srv -a --email "lego@example.com" --eab --kid keyid_01 --hmac YW5vdXRoZXJfdmVyeV9sb25nX2htYWNfZm9yX2tleWlkXzAxX3doaWNoIHdpbGxfYmUgdXNlZF9kdXJpbmcgcmVncmVzc2lvbg -d www.example.local --http run
@@ -227,4 +227,35 @@ runs:
       sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout | grep "Issuer: CN = root-ca"
       sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext keyUsage | grep "Digital Signature, Non Repudiation"
       sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Client Authentication, Code Signing"
+    shell: bash
+
+  - name: "EAB - 07b - Enroll acme - challenge validations fails"
+    id: acmefail04
+    continue-on-error: true
+    run: |
+      sudo rm -rf acme-sh/*
+      docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --register-account --server http://acme-srv --accountemail 'acme-sh@example.com' --eab-kid keyid_02 --eab-hmac-key dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM --debug 3
+      docker run --rm -i -v "$(pwd)/acme-sh":/acme.sh --network acme --name=acme-sh neilpang/acme.sh:latest --issue --server http://acme-srv -d www.example.local --standalone --debug 3 --output-insecure
+    shell: bash
+
+  - name: "EAB - 07b - check  result "
+    if: steps.acmefail04.outcome != 'failure'
+    run: |
+      echo "acmefail outcome is ${{steps.acmefail04.outcome }}"
+      exit 1
+    shell: bash
+
+  - name: "EAB - 07b - Enroll lego - challenge validations fails"
+    id: legofail04
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego -s http://acme-srv -a --email "lego@example.com" --eab --kid keyid_02 --hmac dGhpc19pc19hX3ZlcnlfbG9uZ19obWFjX3RvX21ha2Vfc3VyZV90aGF0X2l0c19tb3JlX3RoYW5fMjU2X2JpdHM -d www.example.local --http run
+    shell: bash
+
+  - name: "EAB - 07b - check  result "
+    if: steps.legofail04.outcome != 'failure'
+    run: |
+      echo "legofail outcome is ${{steps.legofail04.outcome }}"
+      exit 1
     shell: bash
