bump

diff --git a/.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile/action.yml b/.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile/action.yml
--- a/.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile/action.yml
+++ b/.github/actions/wf_specific/xca_ca_handler/enroll_acmeprofile/action.yml
@@ -37,6 +37,25 @@ runs:
       sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Client Authentication, Code Signing"
     shell: bash
 
+  - name: "ACME-profile - 03 - Enroll lego with template_name acme (to fail)"
+    id: legoprofilefail01
+    continue-on-error: true
+    run: |
+      sudo rm -rf lego/*
+      docker run -i -v $PWD/lego:/.lego/ --rm --name lego --network acme goacme/lego -s http://acme-srv -a --email "lego@example.com" -d lego.acme --http run --profile template
+      # sudo openssl verify -CAfile cert-2.pem -untrusted cert-1.pem  lego/certificates/lego.acme.crt
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -noout
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext keyUsage | grep "Digital Signature, Non Repudiation"
+      sudo openssl x509 -in lego/certificates/lego.acme.crt -text -ext extendedKeyUsage | grep "TLS Web Client Authentication, Code Signing"
+    shell: bash
+
+  - name: "EAB - 03 - check  result "
+    if: steps.legoprofilefail01.outcome != 'failure'
+    run: |
+      echo "acmefail outcome is ${{steps.legoprofilefail01.outcome }}"
+      exit 1
+    shell: bash
+
   - name: "Delete acme-sh, letsencypt and lego folders"
     run: |
       sudo rm -rf  lego/*
